config/routes.rb
Rails.application.routes.draw do

  get 'notifications/:notification_id' => "notifications#show", as: "notification"

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      get '/current_user' => "users#give_current_user"
      resources :users, only: [:index]
      get '/user/:id' => "users#show"
      resource :users, only: [:update] do
        resources :skills, only: [:create, :index]
        post '/add_skill' => "skills#new"
      end

      resources :project_chats, only: [:create, :index]
      post '/mentorships/create_mentor' => 'mentorships#create_mentor'
      post '/mentorships/accept_mentee' => 'mentorships#accept_mentee'
      get '/mentorships/mentor' => 'mentorships#mentor'
      get '/mentorships/mentee' => 'mentorships#mentee'

      get '/projects/:project_id' => 'projects#show'
    end
  end

  mount ActionCable.server => '/cable'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "sessions#new"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]
  resources :projects

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update ]
  end

  resources :mentorships, only: [:create]
  post '/accept_mentee/:mentorship_id' => "mentorships#accept_mentee", as: "accept_mentee"


  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "projects/:id/approve" => "projects#approve", as: "project_approve"
  get "projects/:id/refuse" => "projects#refuse", as: "project_refuse"
  get "projects/:id/build_squad" => "projects#build_squad", as: "build_squad"
  get "projects/:id/team_members" => "projects#team_members", as: "project_team_members"
  get "projects/:id/edit_skills" => "projects#edit_skills", as: "edit_project_skills"
  patch "projects/:id/update_skills" => "projects#update_skills", as: "update_project_skills"
  get "users/:id/skills" => "users#skills", as: "user_skills"
  post "users/:id/add_skills" => "users#add_skills", as: "add_user_skills"
  get "projects/:invite_id/invite_approve" => "projects#invite_approve", as: "invite_approve"
  get "projects/:invite_id/invite_refuse" => "projects#invite_refuse", as: "invite_refuse"

  # fake send email

  get '/send_email' => "emails#send_email", as: "send_email"

  resources :skills, only: [:index, :create, :show]

  constraints Clearance::Constraints::SignedIn.new do
   root to: "users#show", as: :signed_in_root
  end

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  before_save :generate_private_token

  belongs_to 	:company
  has_many		:user_skills
  has_many		:skills, through: :user_skills
  has_many		:managed_projects, class_name: "Project", foreign_key: "project_owner_id"
  has_many		:approved_or_refused_projects, class_name: "Project", foreign_key: "approved_or_refused_by_id"
  has_many		:project_team_members
  has_many		:projects, through: :project_team_members

  has_many    :mentees, through: :menteeing, source: :mentee
  has_many    :menteeing, foreign_key:'mentor_id', class_name:"Mentorship"

  has_many    :mentors, through: :mentoring, source: :mentor
  has_many    :mentoring, foreign_key:'mentee_id', class_name:"Mentorship"

  has_many    :notifications

  mount_uploader :profile_picture, AvatarUploader

  enum access_level: { staff: 0, manager: 1, admin: 2 }
  before_save :generate_private_token

  private
  def generate_private_token
  	if private_token.blank?
  		pr = SecureRandom.hex(10)
  		while !User.find_by(private_token:pr).nil?
  			pr = SecureRandom.hex(10)
  		end
  		self.private_token = pr
  	end
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
	def show
		user = User.find(params["id"].to_i)
		give_user_info(user)
	end

	def index
		company = current_user.company
		users = User.where("company_id = #{company.id}")
		
		users_array = []
		
		users.each_with_index do |user,i|
			user_hash = user.attributes
			user_hash["profile_picture"] = user.profile_picture.url
			arr = user.skills
			arr = arr.map do |skill|
				skill.attributes
			end
			user_hash["skills_array"] = arr
			users_array << user_hash
		end		
		
		render json:users_array
	end	

	def update
		current_params = params
		current_params.delete("private_token")
		current_params.delete("sessions")
		user = current_user
		if user.update(current_params)
			render status: 201, json:user
		else 
			render status: 422, json:user.errors.messages 
		end
	end

	def give_user_info(user_or_id)
		if user_or_id.class == Integer
			user = User.find(user_id)
		else 
			user = user_or_id
		end
		user_dup = user.attributes
		user_dup["profile_picture"] = user.profile_picture.url
		
		skills = user.skills

		own_project = user.managed_projects 
		own_project_array = give_project_array_of_hashes(own_project,user.id)

		joined_project = user.projects - own_project
		joined_project_array = give_project_array_of_hashes(joined_project,user.id)

		render json:[user_dup,skills,own_project_array,joined_project_array]
	end

	def give_current_user
		give_user_info(current_user)
	end

	private

	def give_project_array_of_hashes(projects,user_id)
		# turn them into array of hashes
		projects_array = projects.map { |project| project.attributes }

		projects.each_with_index do |project,i|
			# extract the roles (could be more than one)
			skill_ids = ProjectTeamMember.joins(:project_skill).where({project_id:project.id,user_id:user_id}).pluck('project_skills.skill_id')
			skills = Skill.where(id:skill_ids)

			# map skills into array of hashes
			skills = skills.map { |skill| skill.attributes } 
			
			# projects_array[i] is hash, so this is inserting values for key 'skills_array' into the hash.
			projects_array[i]['skills_array'] = skills 
		end
		projects_array
	end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	before_action :require_login
	def show
		@user = User.find(params[:id])
		@project = Project.new
	end

	def skills
		@user = User.find(params[:id])
		@current_skills = @user.skills
		@skill = @user.skills.new
	end

	def update
		@user = User.find(params[:id])
		respond_to do |format|
			if params[:user].nil? || params[:user][:profile_picture].nil?
				format.html {
					flash.now[:danger] = "There is no file selected."
					@project = Project.new
					render 'users/show'
				}
				format.js { render:'no_file', status: :unprocessable_entity }
			elsif @user.update(user_params)
				format.html { redirect_back_or user_path(@user) }
				format.js
			else
				format.html {
					flash.now[:danger] = "Invalid file extension, only file of formats .jpg/ .jpeg/ .gif/ .png,/ .tiff are allowed."
					@project = Project.new
					render 'users/show'
				}
				format.js { render:'upload_errors', status: :unprocessable_entity }
			end
		end
	end


	def add_skills
		@user = User.find(params[:id])
		if params[:skill_ids].present?
			params[:skill_ids].each do |skill_id|
				UserSkill.create(user_id: @user.id, skill_id: skill_id)
				flash[:success] = "Your new skill(s) have been added."
			end
		end
		if params[:skill][:skill_name].present?
			skill = Skill.new(skill_name: params[:skill][:skill_name].titleize, category: params[:skill][:category])
			if skill.save
				UserSkill.create(user_id: @user.id, skill_id: skill.id)
				flash[:success] = "Your new skill(s) have been added."
			else
				# errors = []
				# skill.errors.messages.values.each do |msg|
				# 	msg.each do  |m|
				# 		errors << m
				# 	end
				# end
				# flash.alert = errors
				flash[:danger] = skill.errors.full_messages.join(".")
			end
		end
		redirect_to user_skills_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:avatar,:company_id,:first_name,:last_name,:job_title,:department,:profile_picture)
	end

end

app/helpers/api/v1/user_helper.rb
module Api::V1::UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def profile_picture_helper
		if current_user == @user
			image_tag(@user.profile_picture.file.nil? ? "admin.png" : @user.profile_picture.url, class:"img-circle my-img1 center-block", alt:"#{@user.profile_picture.file.nil? ? "Default profile picture" : "Profile picture"}", title:"#{@user.profile_picture.file.nil? ? "Default profile picture" : "Profile picture"}")

		else 
			image_tag(@user.profile_picture.file.nil? ? "admin.png" : @user.profile_picture.url, class:"img-circle my-img1 center-block", alt:"#{@user.profile_picture.file.nil? ? "Default profile picture" : "Profile picture"}", title:"#{@user.profile_picture.file.nil? ? "Default profile picture" : "Profile picture"}")
		end
	end
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/_skills_form.html.erb
<% Skill.distinct.pluck(:category).each do |category| %> 
  <div>
    <%= skills_form.label :category, category.upcase %>
    <%= skills_form.collection_select(:skills, Skill.where(category: category), :id, :skill_name, {include_hidden: false}, {multiple: true, class: "form-control"}) %>
  </div>
<% end %>

app/views/users/accept_mentee.js.erb
var id = <%= @mentorship.id %>
$('#mentorship_' + id).
$('#flash').html('<%= j "#{@mentorship.errors.full_messages.join(". ")}." %>').addClass("alert alert-danger")

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/no_file.js.erb
if ($('.error-message').length >= 1) {
	$('.error-message').fadeOut('slow');
	$('.error-message').remove();
}
$('h1.full-name').before("<p class='error-message' style='display:none;'>There is no file chosen.</p>")
$('.error-message').fadeIn('slow');

app/views/users/show.html.erb
<div class="container" data-turbolinks="false">

  <br><br><br><br>

  <div class="row">
    <div class="col-sm-6">
      <!-- Displays the profile picture. If own profile, able to amend/upload picture. -->
      <%= profile_picture_helper %>
      <% if current_user == @user%>
        <div><a href="" id="edit-icon"><%= image_tag "edit_icon.png", title:"Change profile picture"%></a></div>
        <%= form_for @user, data: { remote:true, type:"script", disable_with: "Uploading.." } do |form|  %>
          <%= form.file_field(:profile_picture) %>
          <%= form.submit "Upload profile picture" %>
        <% end %>
      <% end %>
      <br>
      <h1 class="middle1 full-name">
        <%= @user.first_name %>
        <%= @user.last_name %>
      </h1>
      <h3 class="middle1">
        <%= @user.job_title %>
      </h3><br>
      <div>
        <% if @user == current_user %>
            <%= button_to "Edit Your Skillset", user_skills_path(@user), method: :get, class:"btn btn-primary btn-md btn-block"%>
            <br><br><br>
            <div class="project-show">
              <h1 class="projects_header_bk text-center">
                Your projects
              </h1>
              <hr>
              <% if @user.projects.exists? || @user.managed_projects.exists? %>
                <table>
                  <tr class="row">
                    <th class="col-md-6 projects_sub_bk">Project</th>
                    <th class="col-md-6 projects_sub_bk">Role</th>
                  </tr>
                  <% if @user.managed_projects.exists? %>
                    <% @user.managed_projects.each do |project| %>
                      <tr class="row">
                        <td class="col-md-6"><%= link_to project.title, project_path(project) %></td>
                        <td class="col-md-6">Project owner</td>
                      </tr>
                    <% end %>
                  <% end %>
                  <% if @user.projects.exists? %>
                    <% @user.project_team_members.each do |p| %>
                      <tr class="row">
                        <td class="col-md-6"><%= link_to p.project.title, project_path(p.project) %></td>
                        <td class="col-md-6"><%= p.project_skill.skill.skill_name %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </table>
              <% else %>
                <h2 class="text-center"> You are not part of any projects, why not start one?</h2>
              <% end %>
            </div>
            <div>
              <h1 class="projects_header_bk text-center">
                Your project invites
              </h1>
              <hr>
              <% if @user.project_team_members.where(status: "awaiting_confirmation").exists? %>
                <table>
                  <tr class="row">
                    <th class="col-md-6 projects_sub_bk">Project</th>
                    <th class="col-md-4 projects_sub_bk">Project Manager</th>
                  </tr>
                  <% @user.project_team_members.where(status: "awaiting_confirmation").each do |invite| %>
                    <tr class="row">
                      <td class="col-md-6"><%= link_to invite.project.title, project_path(invite.project) %></td>
                      <td class="col-md-4"><%= link_to "#{invite.project.project_owner.first_name} #{invite.project.project_owner.last_name}", user_path(invite.project.project_owner) %></td>
                      <td class="col-md-1">
                        <%= link_to "Accept", invite_approve_path(invite), class: "btn btn-primary "%>
                      </td>
                      <td class="col-md-1">
                        <%= link_to "Refuse", invite_refuse_path(invite), class: "btn btn-primary "%>
                      </td>
                    </tr>
                  <% end %>
                </table>
              <% else %>
                <h2 class="text-center"> You have no outstanding project invites. </h2>
              <% end %>
            </div>

          <% end %>
        </div>
        <h1 class="projects_header_bk text-center">Your mentor requests</h1>
        <hr>
        <% if @user.mentors.exists? %>
            <% @user.mentors.each do |user| %>
              <tr class="row">
                <td class="col-md-6"> <%= "#{user.first_name} #{user.last_name}"%> </td>
                <td class="col-md-6"> <%= user.department %> </td>
              </tr>
            <% end %>
          <% else %>
          <h4> No mentor requests </h4>
        <% end %>
        <h1 class="projects_header_bk text-center">Requests for your mentorship</h1>
        <hr>
        <% if @user.mentees.exists? %>
            <% @user.mentees.each do |user| %>
              <div class="row">
                <div class="col-md-6"> <%= "#{user.first_name} #{user.last_name}"%> </div>
                <div class="col-md-4"> <%=  user.first_name %> </div>
                <div class="col-md-2"> <%=  user.first_name %> </div>
              </div>
              <div class="row">
                <div class="col-md-6"> <%= "#{user.first_name} #{user.last_name}"%> </div>
                <div class="col-md-4"> <%=  user.first_name %> </div>
                <div class="col-md-2"> <%=  user.first_name %> </div>
              </div>
              <div class="row">
                <div class="col-md-6"> <%= "#{user.first_name} #{user.last_name}"%> </div>
                <div class="col-md-4"> <%=  user.first_name %> </div>
                <div class="col-md-2"> <%=  user.first_name %> </div>
              </div>
            <% end %>
          <% else %>
          <h4> No requests for mentorship </h4>
        <% end %>
    </div>

    <div class="col-sm-6">
      <% if current_user == @user %>
        <h1 class="middle1">
          What's your project?
        </h1>
        <%= form_for @project do |form| %>
          <div class="form-group">

            <div>
              <%= form.label :title, "Project Name" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>

            <div>
              <%= form.label :description, "Project Description" %>
              <%= form.text_area :description, class: "form-control", rows: "3"%>
            </div>

            <h1 class="middle1">
              Choose skills needed for project
            </h1>
            <%= render partial: 'users/skills_form', object: form %>
            <br>

            <div>
              <%= form.submit @user.staff? ? "Submit for Approval": "Build Squad", class: "btn btn-primary btn-lg btn-block" %>
            </div>

          </div>
        <% end %>
      <% else %>
        <div class="project-show">
          <h1 class="projects_header_bk">
            <%= "#{@user.first_name}'s projects" %>
          </h1>
          <hr>
          <% if @user.projects.exists? || @user.managed_projects.exists? %>
            <table>
              <tr class="row">
                <th class="col-md-6 projects_sub_bk">Project</th>
                <th class="col-md-6 projects_sub_bk">Role</th>
              </tr>
              <% if @user.managed_projects.exists? %>
                <% @user.managed_projects.each do |project| %>
                  <tr class="row">
                    <td class="col-md-6"><%= link_to project.title, project_path(project) %></td>
                    <td class="col-md-6">Project owner</td>
                  </tr>
                <% end %>
              <% end %>
              <% if @user.projects.exists? %>
                <% @user.project_team_members.each do |p| %>
                  <tr class="row">
                    <td class="col-md-4"><%= link_to p.project.title, project_path(p.project) %></td>
                    <td class="col-md-4"><%= p.project_skill.skill.skill_name %></td>
                    <td class="col-md-4"><%= p.status.titleize %></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          <% else %>
            <h1><%= @user.first_name %> is not part of any projects!</h1>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>
<br>

<% if current_user == @user %>
  <div class="container-fluid user_darkblue">

    <% if @user.staff? %>
      <div class="container-fluid user_darkblue">
        <div class="container user_darkblue">
          <div class="row">

            <div class=" col-md-6 user_darkblue">
              <div>
                <h2 class="user_title_desc">
                  Pending Approval
                </h2>
              </div>
              <% @user.managed_projects.where(status: "awaiting_approval").each do |project| %>
                <div class="pmd-card pmd-card-default pmd-z-depth">
                  <div class="pmd-card-body">
                    <h2>
                      <%= link_to project.title, project_path(project) %>
                    </h2>
                  </div>
                </div>
              <% end %>
            </div>

            <div class=" col-md-6 user_darkblue fix-this">
              <div>
                <h1 class="user_title_desc">
                  Create Team
                </h1>
              </div>
              <% @user.managed_projects.where(status: "approved").each do |project| %>
                <% if project.users.empty? %>
                  <div class="pmd-card pmd-card-default pmd-z-depth">
                    <div class="pmd-card-body">
                      <table>
                        <tr>
                          <td width="400">
                            <h2>
                              <%= link_to project.title, project_path(project) %>
                            </h2>
                          </td>
                          <td>
                            <%= link_to "Build Squad", build_squad_path(project), class: "btn btn-primary" %>
                          </td>
                        </tr>
                      </table>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    <% else %>
      <div class="container-fluid user_darkblue">
        <div class="container user_darkblue">
          <div class="row">
            <div class="col-md-6 user_darkblue">
              <table>
                <div>
                  <h1 class="user_title_desc">
                    Projects Pending Your Approval
                  </h1>
                </div>
                <% Project.where(status: "awaiting_approval").each do |project| %>
                  <% if project.project_owner.department == @user.department %>
                    <div class="col-sm-6 user_darkblue">
                      <div class="pmd-card pmd-card-default pmd-z-depth card_height">
                        <div class="pmd-card-body">
                          <h2>
                            <div class="enlarge_text">
                              <%= link_to project.title, project_path(project) %>
                            </div>
                            <div><br>
                              <%= link_to "Approve", project_approve_path(project), class: "btn btn-primary "%>
                              <%= link_to "Refuse", project_refuse_path(project), class: "btn btn-primary" %>
                            </div>
                          </h2>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </table>
            </div>
            <div class=" col-md-6 user_darkblue">
              <h1 class="user_title_desc">
                Projects You've Approved
              </h1>
              <% Project.where(status: "approved", approved_or_refused_by_id: "#{@user.id}").each do |project| %>
                <div class="col-sm-4 user_darkblue">
                  <div class="pmd-card pmd-card-default pmd-z-depth card_height_approved">
                    <div class="pmd-card-body">
                      <%= link_to project.title, project_path(project) %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<br><br><br><br><br><br>

app/views/users/skills.html.erb
<% if @errors %>
  <% @errors.each do |attr,msg| %>
      <li><%= msg %></li>
  <% end %>
<% end %>


<div class="container-fluid user_darkblue user_skill_height">
  <div class="container user_darkblue">
      <h1 class="user_skills_title_desc"> Your skills </h1>
      <hr>
      <% @current_skills.pluck(:category).uniq.in_groups_of(3, false).each do |group| %>
        <div class="row">
          <% group.each do |category| %>
            <div class="category col-md-4">
              <h2 class="userssub user_skills_sub"> <%= category %> </h2>
              <% @current_skills.where(category: category).each do |skill| %>
                <h2 class="user_skills_info"><%= skill.skill_name %></h2>
              <% end %>
              </br>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <br><br><br>
</div>

  <div class="container">
    <hr size="10">

      <div>
        <%= form_for @skill, url: add_user_skills_path do |form| %>
          <div>
            <h1> Add skill(s) to your portfolio </h1>
            <% Skill.distinct.pluck(:category).each do |category| %>
              <div>
                <%= form.label :category, category.upcase %>
                <%= form.collection_select(:skill_name, Skill.where(category: category).where.not(id: @current_skills.ids), :id, :skill_name, {include_hidden: false}, {name: "skill_ids[]", multiple: true, class: "form-control"}) %>
              </div>
            <% end %>
            </br>
            <div> <h2> Have a skill that isn't listed? </h2>
              <div>
                <%= form.label :category, "Category" %>
                <%= form.select(:category, (Skill.distinct.pluck(:category)), {prompt: "Please choose a category"}, {class: "form-control"})%>
              </div>
               <div>
                <%= form.label :skill, "Skill" %>
                <%= form.text_field :skill_name, class: "form-control" %>
              </div>
            </div>
            </br>
            <div>
              <%= form.submit "Add skill(s)", class: "btn btn-primary btn-lg btn-block" %>
            </div>
          </div>
        <% end %>
      </div>
      <br><br><br><br>
  </div>

app/views/users/update.js.erb
alert("hello")
$("img[alt='Profile picture']").prop('src','<%= j @user.profile_picture.url %>')

app/views/users/upload_errors.js.erb
if ($('.error-message').length >= 1) {
	$('.error-message').fadeOut('slow'); 
	$('.error-message').remove();
}
$('h1.full-name').before("<p class='error-message' style='display:none;'>Wrong file extension.</p>")
$('.error-message').fadeIn('slow');