config/routes.rb
Rails.application.routes.draw do

  get 'notifications/:notification_id' => "notifications#show", as: "notification"

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      get '/current_user' => "users#give_current_user"
      resources :users, only: [:index]
      get '/user/:id' => "users#show"
      resource :users, only: [:update] do
        resources :skills, only: [:create, :index]
        post '/add_skill' => "skills#new"
      end

      resources :project_chats, only: [:create, :index]
      post '/mentorships/create_mentor' => 'mentorships#create_mentor'
      post '/mentorships/accept_mentee' => 'mentorships#accept_mentee'
      get '/mentorships/mentor' => 'mentorships#mentor'
      get '/mentorships/mentee' => 'mentorships#mentee'

      get '/projects/:project_id' => 'projects#show'
    end
  end

  mount ActionCable.server => '/cable'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "sessions#new"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]
  resources :projects

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update ]
  end

  resources :mentorships, only: [:create]
  post '/accept_mentee/:mentorship_id' => "mentorships#accept_mentee", as: "accept_mentee"


  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "projects/:id/approve" => "projects#approve", as: "project_approve"
  get "projects/:id/refuse" => "projects#refuse", as: "project_refuse"
  get "projects/:id/build_squad" => "projects#build_squad", as: "build_squad"
  get "projects/:id/team_members" => "projects#team_members", as: "project_team_members"
  get "projects/:id/edit_skills" => "projects#edit_skills", as: "edit_project_skills"
  patch "projects/:id/update_skills" => "projects#update_skills", as: "update_project_skills"
  get "users/:id/skills" => "users#skills", as: "user_skills"
  post "users/:id/add_skills" => "users#add_skills", as: "add_user_skills"
  get "projects/:invite_id/invite_approve" => "projects#invite_approve", as: "invite_approve"
  get "projects/:invite_id/invite_refuse" => "projects#invite_refuse", as: "invite_refuse"

  # fake send email

  get '/send_email' => "emails#send_email", as: "send_email"

  resources :skills, only: [:index, :create, :show]

  constraints Clearance::Constraints::SignedIn.new do
   root to: "users#show", as: :signed_in_root
  end

end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to	:project_owner, class_name: "User"
	belongs_to	:approved_or_refused_by, class_name: "User", optional: true
	has_many		:project_skills
	has_many		:skills, through: :project_skills
	has_many		:users, through: :project_team_members
	has_many		:project_team_members
	has_many 		:project_chats
	enum status: { awaiting_approval: 0, approved: 1, refused: 2, complete: 3 }
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::ApplicationController
	def show
		project = Project.find(params[:project_id].to_i)
		project_team_members = project.users
		project_owner = project.project_owner
		project_team_members = [project_owner] + project_team_members
		project_team_members_arr = []
		project_team_members.each do |user|
			u = user.attributes
			u["profile_picture"] = {"url":user.profile_picture.url}
			project_team_members_arr << u
		end
		render json:project_team_members_arr
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_login

	def create
		@project = current_user.managed_projects.new(project_params)
		@project.skills = Skill.where(id: params[:project][:skills])
		if !current_user.staff?
			@project.approved!
			@project.approved_or_refused_by = current_user
			if @project.save
				redirect_to build_squad_path(@project)
			end
		else
			name = "#{current_user.first_name} #{current_user.last_name}"
			company = current_user.company
			if @project.save
				managers = company.users.where(department:current_user.department)
				if managers.exists?
					manager = managers.first
					notification = manager.notifications.new(notification_message:"#{name} from your department has a new project pending for your approval.")
				else
					# if no manager, HR manager to approve
					manager = company.users.where(access_level:"admin").first
					notification = manager.notifications.new(notification_message:"#{name} from #{current_user.department} has a new project pending for approval.")
				end

				if notification.save
					ActionCable.server.broadcast "notifications_#{manager.id}",
						message: notification.notification_message,
						id: notification.id
				end

				redirect_to "/"
			end
		end
	end

	def index
		company = current_user.company
		@projects = []
		Project.all.each do |project|
			@projects << project if project.project_owner.company == company
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	def approve
		@project = Project.find(params[:id])
		@project.approved!
		@project.approved_or_refused_by = current_user
		project_owner = @project.project_owner
		if @project.save
			notification = project_owner.notifications.new(notification_message:"Your project #{@project.title} has been approved by your manager #{current_user.first_name}.")
			if notification.save
				ActionCable.server.broadcast "notifications_#{project_owner.id}",
					message: notification.notification_message,
					id: notification.id
			end
			redirect_to "/"
		end
	end

	def refuse
		@project = Project.find(params[:id])
		@project.refused!
		@project.approved_or_refused_by = current_user
		project_owner = @project.project_owner
		if @project.save
			notification = project_owner.notifications.new(notification_message:"Your project #{@project.title} has been declined by your manager #{current_user.first_name}.")
			if notification.save
				ActionCable.server.broadcast "notifications_#{project_owner.id}",
					message: notification.notification_message,
					id: notification.id
			end
			redirect_to "/"
		end
	end

	def build_squad
		@project = Project.find(params[:id])
	end

	def team_members
		@project = Project.find(params[:id])
		@project.skills.ids.each do |skill_id|
			project_skill_id = ProjectSkill.find_by(skill_id: skill_id, project_id: @project.id).id
			if params["#{skill_id}"]
				params["#{skill_id}"].each do |user_id|
					team_member = ProjectTeamMember.create(project_id: @project.id, user_id: user_id, project_skill_id: project_skill_id)
					notification = User.find(user_id).notifications.new(notification_message:"You have been invited to the project #{@project.title}and your role would be on #{Skill.find(skill_id).skill_name}.")
					if notification.save
						ActionCable.server.broadcast "notifications_#{user_id}",
							message: notification.notification_message,
							id: notification.id
					end
				end
			end
		end
		redirect_to @project
	end

	def invite_approve
		invite = ProjectTeamMember.find(params[:invite_id])
		invite.status = "confirmed"
		if invite.save
			redirect_to "/"
		end
	end
	
	def invite_refuse
		invite = ProjectTeamMember.find(params[:invite_id])
		invite.status = "invite_refused"
		if invite.save
			redirect_to "/"
		end
	end

	def edit_skills
		@project = Project.find(params[:id])
	end

	def update_skills
		@project = Project.find(params[:id])
		@project.skills = Skill.where(id: params[:project][:skills])
		if @project.save
			redirect_to build_squad_path(@project)
		end
	end

	private

  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/build_squad.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3 index_biege middle">
		</div>
		<div class="col-md-6 index_biege middle">
			<br><br><br>
			<div class="herotext_squad">Build Your Dream Team </div>
						<hr>
			<div class="subtext"> Project: <%= @project.title %> </div>

		</div>
		<div class="col-md-3 index_biege middle">
		</div>
	</div>
</div>


<div class="container-fluid index_darkblue">
	<div class="row">
		<div class="col-sm-3">
		</div>
				<div class="col-sm-6 middle">
						<h1 class="herotext_squad"> Select your team below</h1>
				</div>
		<div class="col-sm-3">
		</div>
	</div>
	<br><br><br>
	<%= form_for @project, url: project_team_members_path, method: "get" do |form| %>
		<div class="row">
			<% @project.skills.each do |skill| %>
				<div class="col-sm-3">
					<%= image_tag "Staff#{[1,2,3,4,5].sample}.png", class: "card_img" %>
					<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form skills_card" style="height: 250px">
						<h2 class="pmd-card-title-text"><%= skill.skill_name %> </h2>
						</br>
						<% skill.users.where.not(id: current_user.id).each do |user| %>
							<div>
								<label>
									<table>
										<tr>	
											<td width="1000">
												<%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
											</td>
											<td>
  											<%= form.check_box :users, { multiple: true, name: "#{skill.id}[]"}, user.id, nil %>
  										</td>
  										<td>
  											&nbsp;&nbsp;&nbsp;
  										</td>
										</tr>
									</table>
								</label>
							</div>
						<% end %>
						<hr>
					</div>
				</div>
			<% end %>
		</div>
	</div>


	<div class="row">
		<div class="col-md-3 middle">
		</div>
		<div class="col-md-6 middle">
			<br><br><br>
			<%= form.submit "Select Team!", class:"btn btn-primary btn-lg btn-block submit-field" %>
		</div>
	<% end %>
	</div>
	<div class="row">
		<div class="col-md-3 middle">
		</div>
		<div class="col-md-6 middle">
		</br>
			<%= button_to "Tweak your skill needs", edit_project_skills_path(@project), method: :get, class:"btn btn-primary btn-lg btn-block submit-field" %>
		</div>
	</div>
</div>
<br>
<br>
<br>

app/views/projects/edit_skills.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3 middle">
		</div>
		<div class="col-md-6 middle">
			<br><br>
			<h1 class="herotext_tweak"> Edit the skills required for your project </h1>
			<br><br>
		</div>
		<div class="col-md-3 middle">
		</div>
	</div>
</div>


<div class="container-fluid">
			<%= form_for @project, url: update_project_skills_path do |form| %>
				<% Skill.distinct.pluck(:category).each do |category| %>
				  <div>
				    <%= form.label :category, category.upcase %>
				    <%= form.collection_select(:skills, Skill.where(category: category), :id, :skill_name, {include_hidden: false, selected: @project.skills.where(category: category).map(&:id)}, {multiple: true, class: "form-control"}) %>
				  </div>
				<% end %>
				</br>
				<div>
			    <%= form.submit "Confirm changes", class: "btn btn-primary btn-lg btn-block" %>
			  </div>
			<% end %>
</div>

app/views/projects/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 index_biege middle">
      <br>
      <div class="herotext">
        All Projects
      </div>
        <div class="subtext">
          View all projects your company is working on.
        </div>
    </div>
    <div class="col-md-6 index_blue3 middle">
      <%= image_tag "projects_top.png", class:"my-img center-block"  %>
    </div>
  </div>
</div>
<div class="container-fluid index_darkblue">
  <div class="container-fluid">
    <div class="row">
      <% @projects.each do |project| %>
      <div class="col-md-3">
        <%= image_tag "projects.png", class: "card_img" %>
        <div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form skills_card project-card">
          <div>
            <h2 class="pmd-card-title-text">
              <%= project.title %>
            </h2>
            <span class="pmd-card-subtitle-text">
              <%= project.description %>
            </span>
          </div>
          <div>
                <%= button_to "See Project", project_path(project), method: :get, class:"btn pmd-ripple-effect btn-primary  btn-md skill_element skills_button_proj "%>
          </div>
        </div>
      </div>

      <%end%>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid">
    <div class="row row_darkblue">
        <div class="col-md-6 projects_darkblue">
            <h1 class= "projects_title_desc">
              Project Name
            </h1>
            <h1 class= "projects_title">
              <%= @project.title %>
            </h1>
            <hr>
            <h4 class="projects_header">
                <%= @project.description %>
            </h4>
            <h3 class="projects_sub">
              Status: <%= @project.status.titleize %>
            </h3>
        </div>

        <div class="col-md-6 projects_blue2">
          <h1 class= "projects_title_desc_bk">
            Project Manager
          </h1>
          <h1 class="projects_title_bk" >
            <%= @project.project_owner.first_name %>
            <%= @project.project_owner.last_name %>
          </h1>
              <hr>
            <h2 class="projects_header_bk"> Skills Required </h2>
              <% @project.skills.each do |skill| %>
                <div class= "container-fluid">
                  <div class="col-md-4 projects_sub_bk">
                    <%= skill.skill_name %>
                  </div>
                </div>
              <% end %>

          <% if @project.users.exists? %>
            <table>
              <tr>
                <h1 class="projects_header_bk"> Team Members </h1>
              <tr>
              <% @project.users.each do |user| %>
                <tr>
                  <td><%= user.first_name %> <%= user.last_name %> </td>
                  <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                  <td><%= ProjectTeamMember.find_by(project_id: @project.id, user_id: user.id).status.titleize %> </td>
                </tr>
              <% end %>
            </table>
          <% end %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 middle projects_beige">
    </div>
    <div class="col-md-4 middle projects_beige">
      <br><br><br>
      <%= button_to "Back to Profile", user_path(current_user), method: "get", class: "btn btn-primary btn-lg btn-block" %>
      <br>
      <%= button_to "Back to All Projects", projects_path, method: "get", class: "btn btn-primary btn-lg btn-block" %>
    </div>
    <div class="col-md-4 middle projects_beige">
    </div>
  </div>
</div>