config/routes.rb
Rails.application.routes.draw do

  get 'notifications/:notification_id' => "notifications#show", as: "notification"

  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      get '/current_user' => "users#give_current_user"
      resources :users, only: [:index]
      get '/user/:id' => "users#show"
      resource :users, only: [:update] do
        resources :skills, only: [:create, :index]
        post '/add_skill' => "skills#new"
      end

      resources :project_chats, only: [:create, :index]
      post '/mentorships/create_mentor' => 'mentorships#create_mentor'
      post '/mentorships/accept_mentee' => 'mentorships#accept_mentee'
      get '/mentorships/mentor' => 'mentorships#mentor'
      get '/mentorships/mentee' => 'mentorships#mentee'

      get '/projects/:project_id' => 'projects#show'
    end
  end

  mount ActionCable.server => '/cable'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "sessions#new"

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]
  resources :projects

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update ]
  end

  resources :mentorships, only: [:create]
  post '/accept_mentee/:mentorship_id' => "mentorships#accept_mentee", as: "accept_mentee"


  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "projects/:id/approve" => "projects#approve", as: "project_approve"
  get "projects/:id/refuse" => "projects#refuse", as: "project_refuse"
  get "projects/:id/build_squad" => "projects#build_squad", as: "build_squad"
  get "projects/:id/team_members" => "projects#team_members", as: "project_team_members"
  get "projects/:id/edit_skills" => "projects#edit_skills", as: "edit_project_skills"
  patch "projects/:id/update_skills" => "projects#update_skills", as: "update_project_skills"
  get "users/:id/skills" => "users#skills", as: "user_skills"
  post "users/:id/add_skills" => "users#add_skills", as: "add_user_skills"
  get "projects/:invite_id/invite_approve" => "projects#invite_approve", as: "invite_approve"
  get "projects/:invite_id/invite_refuse" => "projects#invite_refuse", as: "invite_refuse"

  # fake send email

  get '/send_email' => "emails#send_email", as: "send_email"

  resources :skills, only: [:index, :create, :show]

  constraints Clearance::Constraints::SignedIn.new do
   root to: "users#show", as: :signed_in_root
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>SquadUp</title>
    <%= csrf_meta_tags %>

    <!-- Open Sans login-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <!--Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= action_cable_meta_tag %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


  <body>
    <% if signed_in? %>


  <!-- Bootstrap basic Navbar -->
  <nav class="navbar1 navbar-inverse parallax_nav" >
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <%= image_tag("company_logo.png", size:'60x60') %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <%= button_to "Sign Out", sign_out_path, method: :delete, class:"btn btn-primary btn-md btn-block" %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= button_to "Training", skills_path, method: :get, class:"btn btn-primary btn-md btn-block" %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= button_to "Profile", user_path(current_user), method: :get, class:"btn btn-primary btn-md btn-block" %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= button_to "All Projects", projects_path, method: :get, class:"btn btn-primary btn-md btn-block" %>
        </ul>
        <ul class="nav navbar-nav navbar-right dropdown">
          
          <% count = current_user.notifications.where(read_status:0).count %>
          <button type="button" class="btn btn-primary btn-md btn-block dropdown-toggle notification-button" data-toggle="dropdown">Notifications (<%=count%>)</button>
          <ul class="dropdown-menu append-notification-dropdown">
            <% if count === 0 %>
              <li class='default-notification'>
                <a>You have no new notifications for now.</a>
              </li>
            <% else %>
              <% unread_notification_ordered_list.each do |n| %>
                <li><%= link_to n.notification_message, notification_path(n) %></li>
              <% end %>
            <% end %>
            <% read_notification_ordered_list.each do |n| %>
              <li class="read-notification"><%= n.notification_message %></li>
            <% end %>
        
          </ul>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
    <% end %>
  <div id="flash">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>


    <%= yield %>

  </body>

</html>